// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/socialite/socialite.proto

package socialite

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Request struct {
	Driver               string   `protobuf:"bytes,1,opt,name=driver,proto3" json:"driver,omitempty"`
	Callback             string   `protobuf:"bytes,2,opt,name=callback,proto3" json:"callback,omitempty"`
	Code                 string   `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	State                string   `protobuf:"bytes,4,opt,name=state,proto3" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_4e1f10f4ce6750b2, []int{0}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetDriver() string {
	if m != nil {
		return m.Driver
	}
	return ""
}

func (m *Request) GetCallback() string {
	if m != nil {
		return m.Callback
	}
	return ""
}

func (m *Request) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *Request) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

type Response struct {
	Url                  string   `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Token                string   `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	Valid                bool     `protobuf:"varint,4,opt,name=valid,proto3" json:"valid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_4e1f10f4ce6750b2, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *Response) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *Response) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

func init() {
	proto.RegisterType((*Request)(nil), "socialite.Request")
	proto.RegisterType((*Response)(nil), "socialite.Response")
}

func init() { proto.RegisterFile("proto/socialite/socialite.proto", fileDescriptor_4e1f10f4ce6750b2) }

var fileDescriptor_4e1f10f4ce6750b2 = []byte{
	// 218 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x90, 0xc1, 0x4e, 0x84, 0x30,
	0x10, 0x86, 0x5d, 0x77, 0x65, 0x61, 0x4e, 0x66, 0x34, 0xa6, 0xd9, 0x8b, 0x86, 0x93, 0xa7, 0x35,
	0x11, 0x5f, 0xc0, 0x1b, 0x07, 0x4f, 0x35, 0x3e, 0x40, 0x69, 0x27, 0xda, 0xd0, 0x50, 0x6c, 0x0b,
	0xcf, 0x6f, 0x68, 0x2b, 0xc4, 0xa3, 0xb7, 0xff, 0xfb, 0x26, 0xc3, 0xcf, 0x14, 0xee, 0x47, 0x67,
	0x83, 0x7d, 0xf2, 0x56, 0x6a, 0x61, 0x74, 0xa0, 0x2d, 0x9d, 0xe3, 0x04, 0xab, 0x55, 0xd4, 0x9f,
	0x70, 0xe4, 0xf4, 0x3d, 0x91, 0x0f, 0x78, 0x07, 0x85, 0x72, 0x7a, 0x26, 0xc7, 0x76, 0x0f, 0xbb,
	0xc7, 0x8a, 0x67, 0xc2, 0x13, 0x94, 0x52, 0x18, 0xd3, 0x09, 0xd9, 0xb3, 0xcb, 0x38, 0x59, 0x19,
	0x11, 0x0e, 0xd2, 0x2a, 0x62, 0xfb, 0xe8, 0x63, 0xc6, 0x5b, 0xb8, 0xf2, 0x41, 0x04, 0x62, 0x87,
	0x28, 0x13, 0xd4, 0x2d, 0x94, 0x9c, 0xfc, 0x68, 0x07, 0x4f, 0x78, 0x0d, 0xfb, 0xc9, 0x99, 0x5c,
	0xb3, 0xc4, 0x65, 0x27, 0xd8, 0x9e, 0x86, 0x5c, 0x90, 0x60, 0xb1, 0xb3, 0x30, 0x5a, 0xc5, 0x2f,
	0x95, 0x3c, 0xc1, 0xf3, 0x0c, 0xd5, 0xfb, 0xef, 0xff, 0xe3, 0x0b, 0x1c, 0x5f, 0xa7, 0xf0, 0xf5,
	0xc1, 0xdf, 0x10, 0xcf, 0xdb, 0x9d, 0xf9, 0xa6, 0xd3, 0xcd, 0x1f, 0x97, 0xea, 0xeb, 0x0b, 0x6c,
	0xa0, 0x68, 0xc5, 0xa0, 0x0c, 0xfd, 0x63, 0xa9, 0x2b, 0xe2, 0xe3, 0x35, 0x3f, 0x01, 0x00, 0x00,
	0xff, 0xff, 0x4a, 0x59, 0x1d, 0x47, 0x5f, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Socialite service

type SocialiteClient interface {
	// 授权网址
	AuthURL(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	Handle(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
}

type socialiteClient struct {
	c           client.Client
	serviceName string
}

func NewSocialiteClient(serviceName string, c client.Client) SocialiteClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "socialite"
	}
	return &socialiteClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *socialiteClient) AuthURL(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "Socialite.AuthURL", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialiteClient) Handle(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "Socialite.Handle", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Socialite service

type SocialiteHandler interface {
	// 授权网址
	AuthURL(context.Context, *Request, *Response) error
	Handle(context.Context, *Request, *Response) error
}

func RegisterSocialiteHandler(s server.Server, hdlr SocialiteHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&Socialite{hdlr}, opts...))
}

type Socialite struct {
	SocialiteHandler
}

func (h *Socialite) AuthURL(ctx context.Context, in *Request, out *Response) error {
	return h.SocialiteHandler.AuthURL(ctx, in, out)
}

func (h *Socialite) Handle(ctx context.Context, in *Request, out *Response) error {
	return h.SocialiteHandler.Handle(ctx, in, out)
}
