// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/user/user.proto

package user

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type User struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Origin               string   `protobuf:"bytes,2,opt,name=origin,proto3" json:"origin,omitempty"`
	Openid               string   `protobuf:"bytes,3,opt,name=openid,proto3" json:"openid,omitempty"`
	Session              string   `protobuf:"bytes,4,opt,name=session,proto3" json:"session,omitempty"`
	CreatedAt            string   `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            string   `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetOrigin() string {
	if m != nil {
		return m.Origin
	}
	return ""
}

func (m *User) GetOpenid() string {
	if m != nil {
		return m.Openid
	}
	return ""
}

func (m *User) GetSession() string {
	if m != nil {
		return m.Session
	}
	return ""
}

func (m *User) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *User) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

type Request struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{1}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

type Response struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Users                []*User  `protobuf:"bytes,2,rep,name=users,proto3" json:"users,omitempty"`
	Total                int64    `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	Build                []string `protobuf:"bytes,4,rep,name=build,proto3" json:"build,omitempty"`
	Valid                bool     `protobuf:"varint,5,opt,name=valid,proto3" json:"valid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{2}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *Response) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

func (m *Response) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *Response) GetBuild() []string {
	if m != nil {
		return m.Build
	}
	return nil
}

func (m *Response) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

func init() {
	proto.RegisterType((*User)(nil), "user.User")
	proto.RegisterType((*Request)(nil), "user.Request")
	proto.RegisterType((*Response)(nil), "user.Response")
}

func init() { proto.RegisterFile("proto/user/user.proto", fileDescriptor_9b283a848145d6b7) }

var fileDescriptor_9b283a848145d6b7 = []byte{
	// 272 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x91, 0x5f, 0x4a, 0xc4, 0x30,
	0x10, 0xc6, 0xed, 0x9f, 0x74, 0xb7, 0x23, 0xec, 0x43, 0x50, 0x09, 0x82, 0x52, 0x0a, 0xca, 0x3e,
	0xad, 0xb0, 0x9e, 0x60, 0xc5, 0x13, 0x04, 0xd6, 0x57, 0xe9, 0x9a, 0x41, 0x02, 0xa5, 0xa9, 0xc9,
	0xd4, 0x63, 0x78, 0x04, 0xcf, 0x2a, 0x99, 0xb4, 0x20, 0x3e, 0xf8, 0xd2, 0xe6, 0xf7, 0xfb, 0x86,
	0x76, 0x3e, 0x02, 0x97, 0xa3, 0x77, 0xe4, 0x1e, 0xa6, 0x80, 0x9e, 0x1f, 0x3b, 0x66, 0x59, 0xc6,
	0x73, 0xfb, 0x9d, 0x41, 0x79, 0x0c, 0xe8, 0xe5, 0x06, 0x72, 0x6b, 0x54, 0xd6, 0x64, 0xdb, 0x5a,
	0xe7, 0xd6, 0xc8, 0x2b, 0xa8, 0x9c, 0xb7, 0xef, 0x76, 0x50, 0x39, 0xbb, 0x99, 0xd8, 0x8f, 0x38,
	0x58, 0xa3, 0x8a, 0xd9, 0x33, 0x49, 0x05, 0xab, 0x80, 0x21, 0x58, 0x37, 0xa8, 0x92, 0x83, 0x05,
	0xe5, 0x0d, 0xc0, 0x9b, 0xc7, 0x8e, 0xd0, 0xbc, 0x76, 0xa4, 0x04, 0x87, 0xf5, 0x6c, 0x0e, 0x14,
	0xe3, 0x69, 0x34, 0x4b, 0x5c, 0xa5, 0x78, 0x36, 0x07, 0x6a, 0x6b, 0x58, 0x69, 0xfc, 0x98, 0x30,
	0x50, 0xfb, 0x95, 0xc1, 0x5a, 0x63, 0x18, 0xdd, 0x10, 0x50, 0xde, 0x02, 0x17, 0xe0, 0x8d, 0xcf,
	0xf7, 0xb0, 0xe3, 0x66, 0xb1, 0x89, 0x66, 0x2f, 0x1b, 0x10, 0xf1, 0x1d, 0x54, 0xde, 0x14, 0x7f,
	0x06, 0x52, 0x20, 0x2f, 0x40, 0x90, 0xa3, 0xae, 0xe7, 0x22, 0x85, 0x4e, 0x10, 0xed, 0x69, 0xb2,
	0xbd, 0x51, 0x65, 0x53, 0x6c, 0x6b, 0x9d, 0x20, 0xda, 0xcf, 0xae, 0xb7, 0x86, 0xd7, 0x5f, 0xeb,
	0x04, 0xfb, 0x17, 0x10, 0x47, 0xfe, 0xd4, 0x1d, 0x88, 0x27, 0x9e, 0xfb, 0xf5, 0x9b, 0xeb, 0x4d,
	0x3a, 0x2f, 0x1b, 0xb7, 0x67, 0xf2, 0x1e, 0xaa, 0x67, 0xec, 0x91, 0xf0, 0xff, 0xb9, 0x53, 0xc5,
	0x37, 0xf4, 0xf8, 0x13, 0x00, 0x00, 0xff, 0xff, 0x7a, 0xeb, 0x4d, 0xbd, 0xba, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Users service

type UsersClient interface {
	// 获取用户绑定账号信息
	Build(ctx context.Context, in *User, opts ...client.CallOption) (*Response, error)
	Delete(ctx context.Context, in *User, opts ...client.CallOption) (*Response, error)
}

type usersClient struct {
	c           client.Client
	serviceName string
}

func NewUsersClient(serviceName string, c client.Client) UsersClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "user"
	}
	return &usersClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *usersClient) Build(ctx context.Context, in *User, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "Users.Build", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersClient) Delete(ctx context.Context, in *User, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "Users.Delete", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Users service

type UsersHandler interface {
	// 获取用户绑定账号信息
	Build(context.Context, *User, *Response) error
	Delete(context.Context, *User, *Response) error
}

func RegisterUsersHandler(s server.Server, hdlr UsersHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&Users{hdlr}, opts...))
}

type Users struct {
	UsersHandler
}

func (h *Users) Build(ctx context.Context, in *User, out *Response) error {
	return h.UsersHandler.Build(ctx, in, out)
}

func (h *Users) Delete(ctx context.Context, in *User, out *Response) error {
	return h.UsersHandler.Delete(ctx, in, out)
}
